# Generated by Django 4.0.3 on 2024-05-09 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_alter_appointment_vin_alter_technician_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='technician',
        ),
        migrations.AddField(
            model_name='appointment',
            name='technicians',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='technicians', to='service_rest.technician'),
        ),
    ]
