# Generated by Django 4.0.3 on 2024-05-09 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_remove_appointment_technician_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='technicians',
        ),
        migrations.AddField(
            model_name='appointment',
            name='technician',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='technician', to='service_rest.technician'),
        ),
    ]
