# Generated by Django 4.0.3 on 2024-05-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0007_rename_date_appointment_set_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='set_time',
            field=models.TimeField(default=None),
        ),
    ]
