# Generated by Django 4.0.3 on 2024-05-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0010_appointment_is_vip'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.TextField(default='pending', max_length=20),
        ),
    ]
